### ISSUE TITLE
Removal of unecessary tooltip on add-registry modal.

### ISSUE THREAD

**Issue by rjerez1992** [Taller-2018-1/core#122]
This is not needed any more. Please remove it.

![image](https://user-images.githubusercontent.com/14122279/44342615-fab8d400-a461-11e8-9916-dfc1beb4af69.png)

**Comment by Vreyesm** [comment]
Removed in #123 , but please verify

**Comment by Alisboa13** [comment]
#123 is on staging. This issue is solved.
