### ISSUE TITLE
Registry validator doesn't cull extra white spaces.

### ISSUE THREAD

**Issue by Alisboa13** [Taller-2018-1/core#70]
The name validator doesn't cull extra white spaces at the end or beginning of the name causing the following:
![image](https://user-images.githubusercontent.com/38052151/41820703-de33ec38-77a3-11e8-97e1-978b591c9c67.png)

**Comment by Alisboa13** [comment]
Steps to replicate, On Indicator 1 of Group 1:
- Add Indicator with name "  Johnson & Johnson"
- Add Indicator with name "Johnson & Johnson  "

**Comment by Vreyesm** [comment]
Is necessary to ignore the spaces between other characters/words?

**Comment by Alisboa13** [comment]
No. If Client/User wants it a new feature request will be created.
